### PR TITLE
First steps for Django2 support

### PR DESCRIPTION
**Pull request by HerrSpace**

### CODE REVIEW

**Comment by nijel** [comment]
Any plans to complete this? I wanted to try serveradmin on Python 3.7 and it fails because Django 1.11 does not work there...

**Comment by HerrSpace** [comment]
Hey nijel! Thanks for your fixes earlier, it's always nice to see interest in our projects. If you have any questions or need help feel free to contact me directly.

Yes this is pretty far up the list. This branch mainly needs rebasing and I think I inadvertently broke django 1.11 support in a few places. I'll pick this back up in a few weeks. Otherwise feel free to pick it up yourself :)

**Comment by nijel** [comment]
This is clearly out of scope for me now. We're just evaluating possible solutions for now and I wanted to make it run. That could be done as well by using older python :-). As I've mentioned at FOSDEM lack of docs is major hurdle when trying to setup this...

**Comment by HerrSpace** [comment]
Indeed, better docs are also fairly high on the list..
I enabled the issue tracker for this project, please create many tickets ;)

**Comment by HerrSpace** [comment]
I think this is in a good state now. I'll first finish the datetime MR now and then rebase the internal stuff for django2.

I'll probably create another release before merging this as it has some breaking changes like the middleware classes variable rename and the api function loader middleware removal. Probably good to split them from the migrations and datatype changes.

**Pull request merged**
