### PR TITLE
Fix ContainedBy filter for IP networks

### PR DESCRIPTION
**Pull request by meikomeik**
Disables IP Network strict mode

### CODE REVIEW

**Review by TuxPowered42 — CHANGES_REQUESTED** [review]
Let's not ignore the user's error and just overwrite the request. The proper way would be to report the error back to the UI and have the user type in proper data.

**Comment by meikomeik** [comment]
I changed the behaviour to not ignore the "<ip> has host bits set" but rather raise it as a FilterValueError.
This way it will be displayed to the user in the serveradmin frontend

**Comment by kofrezo** [comment]
The method `json_to_datatype` is currently only used by the backend in the Servershell (`servershell/results`) and not by the Python API (`api/dataset/qery`) - Probably for historic reasons.

This means the validation only takes place when using the Servershell. 

Refactoring the backend to use the same logic is beyond this PR and so we'll merge this as it already gives a benefit with having the validation in the backend.

**Comment by kofrezo** [comment]
Example of the error message in the Servershell instead of a HTTP status code 500.

Screenshot from 2022-03-30 08-42-55

**Pull request merged**
